Layout
sofimay/ReDI-school pull request #3
Opened 2020-09-28 10:07 UTC by sofimay

2020-09-28 20:30 UTC, MrTim requested changes
Nice start! I left some comments related to code.

2020-09-28 20:30 UTC, MrTim commented on index.html
> +    <style>
Could you please put styles in separate file and connect it to index.html

2020-09-28 20:30 UTC, MrTim commented on index.html
> +            nav ul {
pay attention to indentation. This block should be moved 4 spaces left to be aligned with the rest.

2020-09-28 20:30 UTC, MrTim commented on index.html
> +
too many empty lines

2020-09-28 20:30 UTC, MrTim commented on index.html
> +
you don't need to create an empty line separator

2020-10-02 08:40 UTC, keponk commented
@sofimay seems like this pull request has some conflicts. Normally this happens when git sees changes it doesn't know where it came from, like when we edit something in a different branch but not on this one.
 
Let us know if you need help completing this pull request :)

2020-10-04 11:54 UTC, sofimay commented
> @sofimay seems like this pull request has some conflicts. Normally this happens when git sees changes it doesn't know where it came from, like when we edit something in a different branch but not on this one.
> 
> Let us know if you need help completing this pull request :)

I was wondering, if it won't be better to start a new pull request with all the changes, instead of merging this one?

2020-10-04 12:48 UTC, MrTim commented
@sofimay I think it make sense to fix this pr and merge it. It could be a good practice in resolving the conflicts during merge, because this will happen from time to time.

2020-10-12 20:00 UTC, merged